- hosts: localhost
  gather_facts: false
  vars:
    host: safeguard.example.com
    cacert: /path/ca_bundle.pem
    cert:   /path/appcert.pem
    key:    /path/appkey.pem
    system: CSDevExtDomain
    account: svc.aap_spe_win
  tasks:
    - name: Get secret using custom Authentication header
      set_fact:
        spp_password: >-
          {{ lookup('spp_apikey_authsecret',
                    'Password',            # secret type
                    host=host, cacert=cacert, cert=cert, key=key,
                    system=system, account=account,
                    header_name='Authentication') }}
      no_log: true

    - debug: msg="password length={{ spp_password|length }}"
      no_log: true

